import LoginPage from "@/components/LogingPage/LoginPage";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Bangladesh Bank/login",
  description: "Generated by create next app",
};
const Login = () => {
  return (
    <>
      <LoginPage />
    </>
  );
};

export default Login;
